### ISSUE TITLE
Autopep8 installation is not happening.

### ISSUE THREAD

**Issue by mohandk142** [hhatto/autopep8#147]
I have pep8 1.5.7 installed on my mac.
When I install autopep8 it throws me below error.
Traceback (most recent call last):
  File "/bin/autopep8", line 5, in <module>
   "python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: pep8>=1.5.7

**Comment by stuaxo** [comment]
Hi,
   Just hit this, working in a virtualenv - I've tried everything in the troubleshooting (except sudo - as that would be outside the virtualenv).

S

**Comment by myint** [comment]
@stuaxo, I think we'll need more information than that to be of any help. For example, useful things might be the output of `which autopep8`, `which python`, `python --version`, stack traces, etc..

**Comment by stuaxo** [comment]
installing autopep8

```
$ pip install autopep8
Collecting autopep8
  Using cached autopep8-1.2.tar.gz
Collecting pep8>=1.5.7 (from autopep8)
  Using cached pep8-1.6.2-py2.py3-none-any.whl
Installing collected packages: pep8, autopep8
  Running setup.py install for autopep8
Successfully installed autopep8-1.2 pep8-1.6.2
```

versions:
```
$ python --version
Python 2.7.9
```

```
$ which pep8
/mnt/data/home/stu/.virtualenvs/3d/bin/pep8
```

```
$ which autopep8
/mnt/data/home/stu/.virtualenvs/3d/bin/autopep8
```

output of autopep8
```
$ autopep8
Traceback (most recent call last):
  File "/mnt/data/home/stu/.virtualenvs/3d/bin/autopep8", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2671, in <module>
    working_set.require(__requires__)
  File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pep8>=1.5.7
```


Looking inside the autopep8 script:

```
#!/mnt/data/home/stu/.virtualenvs/3d/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'autopep8==1.2','console_scripts','autopep8'
__requires__ = 'autopep8==1.2'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('autopep8==1.2', 'console_scripts', 'autopep8')()
    )
```


Doing some tracing ...

```
$ python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pkg_resources import load_entry_point
>>> load_entry_point('autopep8==1.2', 'console_scripts', 'autopep8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 305, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2244, in load_entry_point
    return ep.load()
  File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 1953, in load
    if require: self.require(env, installer)
  File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 1966, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pep8>=1.5.7
```

This is interesting:

```
In [8]: pkg_resources.require("setuptools")
Out[8]: [distribute 0.6.14 (/mnt/data/home/stu/.virtualenvs/3d/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg)]
```

But no pep8 !

```
----> 1 pkg_resources.require("pep8")

/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.pyc in require(self, *requirements)
    652         """
    653 
--> 654         needed = self.resolve(parse_requirements(requirements))
    655 
    656         for dist in needed:

/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.pyc in resolve(self, requirements, env, installer, replacement)
    550                         # unfortunately, zc.buildout uses a str(err)
    551                         # to get the name of the distribution here..
--> 552                         raise DistributionNotFound(req)
    553                 to_activate.append(dist)
    554             if dist not in req:

DistributionNotFound: pep8

```


Trying with a fresh virtualenv, new pip and setuptools and it works ..

```
$ mkvirtualenv newenv
Running virtualenv with interpreter /mnt/data/home/stu/.virtualenvs/3d/bin/python2
Using real prefix '/usr'
New python executable in newenv/bin/python2
Also creating executable in newenv/bin/python
Installing setuptools, pip...done.

$ pip install -U setuptools pip
Downloading/unpacking setuptools from https://pypi.python.org/packages/3.4/s/setuptools/setuptools-18.1-py2.py3-none-any.whl#md5=b6c8eae6b3636dd952e71135805ee156
  Downloading setuptools-18.1-py2.py3-none-any.whl (461kB): 461kB downloaded
Downloading/unpacking pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-7.1.0-py2.py3-none-any.whl#md5=b108384a762825ec20345bb9b5b7209f
  Downloading pip-7.1.0-py2.py3-none-any.whl (1.1MB): 1.1MB downloaded
Installing collected packages: setuptools, pip
  Found existing installation: setuptools 12.2
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Found existing installation: pip 1.5.6
    Uninstalling pip:
      Successfully uninstalled pip
Successfully installed setuptools pip
Cleaning up...
 newenv $ 
```

Then I tried with a fresh virtualenv *without* updating pip and setuptools ..  and it works again ..   hmmm.

I've kept the misbehaving venv around, can try and dig into this further if it's helpful.

**Comment by myint** [comment]
@stuaxo, correct me if I am wrong, but I think the troubleshooting link I pointed to earlier covers it. In your problematic virtualenv, the `setuptools` is version `distribute 0.6.14`, which doesn't support wheels. But in your working virtualenv, you are using `setuptools 12.2`, which is much newer and supports wheels. Thus the former fails to load `pep8`, while the latter is fine.

**Comment by stuaxo** [comment]
You're right, and I ended up fixing it ... but it was a bit weird:

```
pip install -I -U setuptools
Collecting setuptools
  Using cached setuptools-18.1-py2.py3-none-any.whl
Installing collected packages: setuptools
Successfully installed setuptools-18.1
```

version is still wrong though...

```
python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> pkg_resources.require("setuptools")
[distribute 0.6.14 (/mnt/data/home/stu/.virtualenvs/3d/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg)]
>>>
```

on a whim I tried using easy_install ... which tried to install the wrong version:

```
easy_install -U setuptools
install_dir /mnt/data/home/stu/.virtualenvs/3d/lib/python2.7/site-packages/
Searching for distribute
Reading http://pypi.python.org/simple/distribute/
Best match: distribute 0.7.3
Downloading https://pypi.python.org/packages/source/d/distribute/distribute-0.7.3.zip#md5=c6c59594a7b180af57af8a0cc0cf5b4a
Processing distribute-0.7.3.zip
Running distribute-0.7.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5lZTLw/distribute-0.7.3/egg-dist-tmp-taX3Z1
warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

Removing distribute 0.6.14 from easy-install.pth file
Adding distribute 0.7.3 to easy-install.pth file

Installed /mnt/data/home/stu/.virtualenvs/3d/lib/python2.7/site-packages/distribute-0.7.3-py2.7.egg
Processing dependencies for distribute
Finished processing dependencies for distribute
```

...then I reran the upgrade with pip again (now in the randomly-trying-things-phase):

```
pip install -I -U setuptools
Collecting setuptools
  Using cached setuptools-18.1-py2.py3-none-any.whl
Installing collected packages: setuptools
Successfully installed setuptools-18.1
```

checked the version and it is correct!

```
python -c "import pkg_resources; print pkg_resources.require('setuptools')"
[setuptools 18.1 (/mnt/data/home/stu/.virtualenvs/3d/lib/python2.7/site-packages)]
```

and autopep8 works

```
autopep8
usage: autopep8 [-h] [--version] [-v] [-d] [-i] [--global-config filename]
                [--ignore-local-config] [-r] [-j n] [-p n] [-a]
                [--experimental] [--exclude globs] [--list-fixes]
                [--ignore errors] [--select errors] [--max-line-length n]
                [--line-range line line] [--indent-size n]
                [files [files ...]]
autopep8: error: incorrect number of arguments
```

Bah, I should've backed up the virtualenv so this would be diagnosable, not sure what the blockage was but it seems to work now.

**Comment by tiantianquan** [comment]
@stuaxo it works, thanks
