### ISSUE TITLE
Multiprocessing broken on Windows since 1.1

### ISSUE THREAD

**Issue by schlamar** [hhatto/autopep8#193]
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\Python27\Lib\multiprocessing\forking.py", line 380, in main
        prepare(preparation_data)
      File "c:\Python27\Lib\multiprocessing\forking.py", line 488, in prepare
        assert main_name not in sys.modules, main_name
    AssertionError: __main__

This is probably an upstream bug but there might be a workaround: http://bugs.python.org/issue10845

**Comment by schlamar** [comment]
Could be this one: https://github.com/pypa/pip/issues/1891

**Comment by myint** [comment]
So #173 caused this? Are we getting any benefits from wheel that make it worth the bugginess?

Thanks
