### ISSUE TITLE
Autopep8 crashes on python 3.5

### ISSUE THREAD

**Issue by AnilRedshift** [hhatto/autopep8#216]
Traceback (most recent call last):
  File "/Users/Anil/.virtualenvs/backend-web/bin/autopep8", line 9, in <module>
    load_entry_point('autopep8==1.2', 'console_scripts', 'autopep8')()
  File "/Users/Anil/.virtualenvs/backend-web/lib/python3.5/site-packages/autopep8.py", line 3622, in main
    fix_multiple_files(args.files, args, sys.stdout)
  File "/Users/Anil/.virtualenvs/backend-web/lib/python3.5/site-packages/autopep8.py", line 3539, in fix_multiple_files
    _fix_file((name, options, output))
  File "/Users/Anil/.virtualenvs/backend-web/lib/python3.5/site-packages/autopep8.py", line 3520, in _fix_file
    fix_file(*parameters)
  File "/Users/Anil/.virtualenvs/backend-web/lib/python3.5/site-packages/autopep8.py", line 2961, in fix_file
    fixed_source = fix_lines(fixed_source, options, filename=filename)
  File "/Users/Anil/.virtualenvs/backend-web/lib/python3.5/site-packages/autopep8.py", line 2922, in fix_lines
    filename=filename)
  File "/Users/Anil/.virtualenvs/backend-web/lib/python3.5/site-packages/autopep8.py", line 3010, in apply_global_fixes
    for (code, function) in global_fixes():
  File "/Users/Anil/.virtualenvs/backend-web/lib/python3.5/site-packages/autopep8.py", line 2987, in global_fixes
    for function in globals().values():

**Comment by AnilRedshift** [comment]
autopep8==1.2

**Comment by AnilRedshift** [comment]
Looks like this is fixed by https://github.com/hhatto/autopep8/pull/197 but that hasn't been released as an image yet. Since 3.5 is officially out now, can you please rev autopep8 to 1.3?

**Comment by myint** [comment]
Thanks for pointing this out. It should be fixed with 73d131e519fd5163993accbaad6b36f7583395f3.

@hhatto, could you upload this to PyPI? Thanks.

**Comment by hhatto** [comment]
version [1.2.1](https://pypi.python.org/pypi/autopep8/1.2.1) has been released.

Thanks
