### ISSUE TITLE
__doc__.split: AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by WscriChy** [hhatto/autopep8#225]
What could be the reason for this exception?

Traceback (most recent call last):
  File "/usr/bin/autopep8", line 9, in <module>
    load_entry_point('autopep8==0.9.1', 'console_scripts', 'autopep8')()
  File "/usr/lib/python2.7/dist-packages/autopep8.py", line 2295, in main
    options, args = parse_args(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/autopep8.py", line 1976, in parse_args
    description=__doc__.split('\n')[0],
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by myint** [comment]
Are you running Python under `-OO` which removes docstrings?

```
$ python -OO autopep8.py
Traceback (most recent call last):
  File "autopep8.py", line 3667, in <module>
    sys.exit(main())
  File "autopep8.py", line 3611, in main
    args = parse_args(argv[1:], apply_config=apply_config)
  File "autopep8.py", line 3131, in parse_args
    parser = create_parser()
  File "autopep8.py", line 3066, in create_parser
    parser = argparse.ArgumentParser(description=docstring_summary(__doc__),
  File "autopep8.py", line 3283, in docstring_summary
    return docstring.split('\n')[0]
AttributeError: 'NoneType' object has no attribute 'split'
```
