### ISSUE TITLE
Exception with multiprocessing on 2.7.11 Windows

### ISSUE THREAD

**Issue by schlamar** [hhatto/autopep8#228]
Traceback (most recent call last):
      File "C:\Users\schlaich\.virtualenvs\main\Scripts\autopep8-script.py", line 9, in <module>
        load_entry_point('autopep8==1.2.1', 'console_scripts', 'autopep8')()
      File "C:\Users\schlaich\.virtualenvs\main\lib\site-packages\autopep8.py", line 3635, in main
        fix_multiple_files(args.files, args, sys.stdout)
      File "C:\Users\schlaich\.virtualenvs\main\lib\site-packages\autopep8.py", line 3549, in fix_multiple_files
        [(name, options) for name in filenames])
      File "c:\Python27\Lib\multiprocessing\pool.py", line 251, in map
        return self.map_async(func, iterable, chunksize).get()
      File "c:\Python27\Lib\multiprocessing\pool.py", line 567, in get
        raise self._value
    AssertionError

**Comment by myint** [comment]
Does `multiprocessing` work in general on CPython 2.7.11 on Windows? (If not, maybe this ought to be reported upstream in CPython's bug tracker.)

**Comment by schlamar** [comment]
Ah, this is the same exception than in #229
