### ISSUE TITLE
Exception on 2.7.11 Windows

### ISSUE THREAD

**Issue by schlamar** [hhatto/autopep8#229]
Traceback (most recent call last):
      File "C:\Users\schlaich\.virtualenvs\main\Scripts\autopep8-script.py", line 9, in <module>
        load_entry_point('autopep8==1.2.1', 'console_scripts', 'autopep8')()
      File "C:\Users\schlaich\.virtualenvs\main\lib\site-packages\autopep8.py", line 3635, in main
        fix_multiple_files(args.files, args, sys.stdout)
      File "C:\Users\schlaich\.virtualenvs\main\lib\site-packages\autopep8.py", line 3552, in fix_multiple_files
        _fix_file((name, options, output))
      File "C:\Users\schlaich\.virtualenvs\main\lib\site-packages\autopep8.py", line 3533, in _fix_file
        fix_file(*parameters)
      File "C:\Users\schlaich\.virtualenvs\main\lib\site-packages\autopep8.py", line 2961, in fix_file
        fixed_source = fix_lines(fixed_source, options, filename=filename)
      File "C:\Users\schlaich\.virtualenvs\main\lib\site-packages\autopep8.py", line 2922, in fix_lines
        filename=filename)
      File "C:\Users\schlaich\.virtualenvs\main\lib\site-packages\autopep8.py", line 3030, in apply_global_fixes
        aggressive=options.aggressive)
      File "C:\Users\schlaich\.virtualenvs\main\lib\site-packages\autopep8.py", line 1277, in fix_w602
        ignore='with_traceback')
      File "C:\Users\schlaich\.virtualenvs\main\lib\site-packages\autopep8.py", line 1234, in refactor
        filename=filename)
      File "C:\Users\schlaich\.virtualenvs\main\lib\site-packages\autopep8.py", line 2667, in refactor_with_2to3
        return unicode(tool.refactor_string(source_text, name=filename))
      File "c:\Python27\Lib\lib2to3\refactor.py", line 380, in refactor_string
        name, err.__class__.__name__, err)
      File "c:\Python27\Lib\lib2to3\refactor.py", line 377, in refactor_string
        tree = self.driver.parse_string(data)
      File "c:\Python27\Lib\lib2to3\pgen2\driver.py", line 106, in parse_string
        return self.parse_tokens(tokens, debug)
      File "c:\Python27\Lib\lib2to3\pgen2\driver.py", line 71, in parse_tokens
        if p.addtoken(type, value, (prefix, start)):
      File "c:\Python27\Lib\lib2to3\pgen2\parse.py", line 127, in addtoken
        assert t < 256
    AssertionError

**Comment by myint** [comment]
What is the input? And does the `lib2to3` tool itself work okay?

**Comment by schlamar** [comment]
This is a pretty weird upstream bug: http://bugs.python.org/issue25918
