### ISSUE TITLE
KeyError: u'count getting started?

### ISSUE THREAD

**Issue by cggaurav** [hhatto/autopep8#353]
```
(x) ☁  services [master] ⚡ autopep8 --in-place --aggressive --aggressive image_precheck.py
Traceback (most recent call last):
  File "/x/bin/autopep8", line 11, in <module>
    sys.exit(main())
  File "/x/lib/python2.7/site-packages/autopep8.py", line 3858, in main
    args = parse_args(argv[1:], apply_config=apply_config)
  File "/x/lib/python2.7/site-packages/autopep8.py", line 3358, in parse_args
    parser = read_config(args, parser)
  File "/x/lib/python2.7/site-packages/autopep8.py", line 3457, in read_config
    opt_type = option_list[norm_opt]
KeyError: u'count'``
```

**Comment by hhatto** [comment]
Thank you for bug reporting.

fix in 8c0dbc1e33cd9d971c881118153667e03a9192fa

Could you try once again with latest master?
