### ISSUE TITLE
E225 - ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by patvdleer** [hhatto/autopep8#391]
```
$ autopep8 -r --in-place src/*
Traceback (most recent call last):
  File "/usr/local/bin/autopep8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/autopep8.py", line 3928, in main
    fix_multiple_files(args.files, args, sys.stdout)
  File "/usr/local/lib/python3.6/dist-packages/autopep8.py", line 3840, in fix_multiple_files
    _fix_file((name, options, output))
  File "/usr/local/lib/python3.6/dist-packages/autopep8.py", line 3821, in _fix_file
    fix_file(*parameters)
  File "/usr/local/lib/python3.6/dist-packages/autopep8.py", line 3210, in fix_file
    fixed_source = fix_lines(fixed_source, options, filename=filename)
  File "/usr/local/lib/python3.6/dist-packages/autopep8.py", line 3190, in fix_lines
    fixed_source = fix.fix()
  File "/usr/local/lib/python3.6/dist-packages/autopep8.py", line 571, in fix
    aggressive=self.options.aggressive))
  File "/usr/local/lib/python3.6/dist-packages/autopep8.py", line 513, in _fix_source
    modified_lines = fix(result)
  File "/usr/local/lib/python3.6/dist-packages/autopep8.py", line 688, in fix_e225
    if not check_syntax(fixed.lstrip()):
  File "/usr/local/lib/python3.6/dist-packages/autopep8.py", line 2908, in check_syntax
    return compile(code, '<string>', 'exec', dont_inherit=True)
ValueError: source code string cannot contain null bytes
```

**Comment by hhatto** [comment]
Thank you for reporting.

Is this PR #386 the same case?

**Comment by hhatto** [comment]
(We are planning to release version 1.3.6 this week.

**Comment by patvdleer** [comment]
Quite possibly, but strangely enough, I can run it with python2.7.
Works:
```
python2.7 -m autopep8 -r --in-place source/*
```

Breaks:
```
python3.6 -m autopep8 -r --in-place source/*
```

**Comment by hhatto** [comment]
Would you please share the repository URL or source code where the error occurred?

**Comment by patvdleer** [comment]
I will on monday morning

**Comment by hhatto** [comment]
waited for a reply and so I will close it.
If there is an update, it will reopen.
