### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 168: ordinal not in range(128)

### ISSUE THREAD

**Issue by dlintw** [hhatto/autopep8#433]
I use autopep8 as pre-commit hook for subversion.  I'm trying check if the input file content is fit for PEP8 by trying to fix it and compare the original file content.( I don't know is there better method)
The python source file contains Chinese utf-8 comments.

pre-commit code(use python to write):
```
193     def is_invalid_pep8(fname):
194         """check is pep8"""
195         org_contents = file_contents(fname, look_cmd)
196         with open("/tmp/autopep8.debug.py", "wb") as f:
197             f.write(org_contents)
198         new_contents = autopep8.fix_code(org_contents, options={'jobs': 0})
199         # sys.stderr.write("org size=%d new_size=%d u(org)size=%d\n" % (
200         #         #    len(org_contents), len(new_contents),
201         #         len(unicode(org_contents,"utf-8"))))
202         return unicode(org_contents, "utf-8") != new_contents
```
Here is the error message
```
ERROR from SVN:
A repository hook failed: Commit blocked by pre-commit hook (exit code 1) with output:
Traceback (most recent call last):
  File "/trac/tfxsvn/hooks/pre-commit", line 243, in <module>
    sys.exit(main())
  File "/trac/tfxsvn/hooks/pre-commit", line 233, in main
    errors += check_py(look_cmd, filelist)
  File "/trac/tfxsvn/hooks/pre-commit", line 205, in check_py
    is_invalid_pep8(ff)]
  File "/trac/tfxsvn/hooks/pre-commit", line 198, in is_invalid_pep8
    new_contents = autopep8.fix_code(org_contents, options={'jobs': 0})
  File "/lib/python2.7/site-packages/autopep8.py", line 3177, in fix_code
    source = source.decode(encoding or get_encoding())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 168: ordinal not in range(128)
W: e2851c1a8e477a3b636c8ad7232bc2977cd5d5fa and refs/remotes/git-svn differ, using rebase:

```

**Comment by hhatto** [comment]
@dlintw 
Could you try to add encoding parameter in `fix_code`?

```
198         new_contents = autopep8.fix_code(org_contents, options={'jobs': 0})
```

fix this:
```
198         new_contents = autopep8.fix_code(org_contents, options={'jobs': 0}, encoding='YOUR-ENCODING')
```

**Comment by dlintw** [comment]
thanks, it works,
