### ISSUE TITLE
TokenError thrown when run against directory

### ISSUE THREAD

**Issue by rameshrvr** [hhatto/autopep8#438]
I ran the autopep8 command against directory, upto v1.3.5 it is working fine. Today i upgraded it to 1.4 and ran and noticed the below error
```
Traceback (most recent call last):
  File "/usr/local/bin/autopep8", line 9, in <module>
    load_entry_point('autopep8==1.4', 'console_scripts', 'autopep8')()
  File "/Library/Python/2.7/site-packages/autopep8.py", line 3993, in main
    fix_multiple_files(args.files, args, sys.stdout)
  File "/Library/Python/2.7/site-packages/autopep8.py", line 3905, in fix_multiple_files
    _fix_file((name, options, output))
  File "/Library/Python/2.7/site-packages/autopep8.py", line 3886, in _fix_file
    fix_file(*parameters)
  File "/Library/Python/2.7/site-packages/autopep8.py", line 3275, in fix_file
    fixed_source = fix_lines(fixed_source, options, filename=filename)
  File "/Library/Python/2.7/site-packages/autopep8.py", line 3255, in fix_lines
    fixed_source = fix.fix()
  File "/Library/Python/2.7/site-packages/autopep8.py", line 571, in fix
    aggressive=self.options.aggressive))
  File "/Library/Python/2.7/site-packages/autopep8.py", line 513, in _fix_source
    modified_lines = fix(result)
  File "/Library/Python/2.7/site-packages/autopep8.py", line 1237, in fix_w605
    tokens = list(generate_tokens(target))
  File "/Library/Python/2.7/site-packages/autopep8.py", line 4015, in generate_tokens
    tokenize.generate_tokens(string_io.readline)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tokenize.py", line 363, in generate_tokens
    raise TokenError, ("EOF in multi-line statement", (lnum, 0))
tokenize.TokenError: ('EOF in multi-line statement', (2, 0))
```
Is there anything i am doing wrong. Or issue with the fix_multiple_files method?
command used `autopep8 --in-place -a -r /Documents/python_test_code/`

**Comment by hhatto** [comment]
@rameshrvr 

This is duplication of #403, #414.
It will release version 1.4.1 in a few days.

Thanks

**Comment by hhatto** [comment]
v1.4.1 released
https://pypi.org/project/autopep8/1.4.1/
