### ISSUE TITLE
tokenize.TokenError: ('EOF in multi-line statement') with the line breaking backslash

### ISSUE THREAD

**Issue by AlexArcPy** [hhatto/autopep8#439]
Having this valid Python code

```python
s = 'result' + '{}'.format('aaa') + 'bbb' + 'ccc' +\
    "\d"
print(s)
```

that executes to

`resultaaabbbccc\d`

throws 

```
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\autopep8.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\autopep8.py", line 3993, in main
    fix_multiple_files(args.files, args, sys.stdout)
  File "c:\python36\lib\site-packages\autopep8.py", line 3905, in fix_multiple_files
    _fix_file((name, options, output))
  File "c:\python36\lib\site-packages\autopep8.py", line 3886, in _fix_file
    fix_file(*parameters)
  File "c:\python36\lib\site-packages\autopep8.py", line 3275, in fix_file
    fixed_source = fix_lines(fixed_source, options, filename=filename)
  File "c:\python36\lib\site-packages\autopep8.py", line 3255, in fix_lines
    fixed_source = fix.fix()
  File "c:\python36\lib\site-packages\autopep8.py", line 571, in fix
    aggressive=self.options.aggressive))
  File "c:\python36\lib\site-packages\autopep8.py", line 513, in _fix_source
    modified_lines = fix(result)
  File "c:\python36\lib\site-packages\autopep8.py", line 1237, in fix_w605
    tokens = list(generate_tokens(target))
  File "c:\python36\lib\site-packages\autopep8.py", line 4015, in generate_tokens
    tokenize.generate_tokens(string_io.readline)
  File "c:\python36\lib\tokenize.py", line 595, in _tokenize
    raise TokenError("EOF in multi-line statement", (lnum, 0))
tokenize.TokenError: ('EOF in multi-line statement', (2, 0))
Process terminated with an exit code of 1
```

when using the `autopep8 1.4 (pycodestyle: 2.4.0)` and Python 3.6.

The cause of the issue is the backslash in the string that follows the breaking line backslash. 

This code won't raise any errors:

```python
s = 'result' + '{}'.format('aaa') + 'bbb' + 'ccc' +\
    "d"
print(s)
```

This code won't raise any errors (adding `r` making a raw string):

```python
s = 'result' + '{}'.format('aaa') + 'bbb' + 'ccc' +\
    r"\d"
print(s)
```

**Comment by hhatto** [comment]
duplication of #438

**Comment by AlexArcPy** [comment]
Oh great, thanks a ton!

**Comment by jaho8** [comment]
tokenize.TokenError: ('EOF in multi-line statement', (231, 0))

The above exception was tokenize.TokenError: ('EOF in multi-line statement', (231, 0))

The above exception was the direct cause of the following exception:

vyper.exceptions.SyntaxException: EOF in multi-line statement
  line 231:0 
       230
  ---> 231
  ---------^the direct cause of the following exception:

vyper.exceptions.SyntaxException: EOF in multi-line statement
  line 231:0 
       230
  ---> 231
  ---------^
