### ISSUE TITLE
Lots of (wrong) code added

### ISSUE THREAD

**Issue by asottile** [hhatto/autopep8#441]
Very simple example:

```python
if True:
    if True:
        if (
                link.is_wheel and
                isinstance(link.comes_from, HTMLPage) and
                link.comes_from.url.startswith(index_url)
        ):
            _store_wheel_in_cache(file_path, index_url)
```

```diff
--- original/t.py
+++ fixed/t.py
@@ -1,8 +1,24 @@
 if True:
     if True:
         if (
-                link.is_wheel and
-                isinstance(link.comes_from, HTMLPage) and
-                link.comes_from.url.startswith(index_url)
+                linkis_wheel and
+            is_wheel and
+            isinstancelinkcomes_fromHTMLPageand and
+            isinstancelinkcomes_fromHTMLPageand and
+            linkcomes_fromHTMLPageand and
+            linkcomes_fromHTMLPageand and
+            comes_fromHTMLPageand and
+            comes_fromHTMLPageand and
+            comes_fromHTMLPageand and
+            comes_fromHTMLPageand and
+            HTMLPageand and
+            HTMLPageand and
+            HTMLPageand and
+            HTMLPageand and
+            HTMLPageand and
+            HTMLPageand and
+            HTMLPageand and
+            HTMLPageand and
+            . (., ) link.comes_from.url.startswith(index_url)
         ):
             _store_wheel_in_cache(file_path, index_url)
```

1.4 seems fine though -- I'll revert

**Comment by asottile** [comment]
A git bisect:

```bash
#!/usr/bin/env bash
set -euxo pipefail

out="$(cd .. && autopep8 --diff t.py 2>&1 || true)"
if grep -q Error: <<< "${out}"; then
    exit 125
fi

if grep -q '^+' <<< "${out}"; then
    exit 1
else
    exit 0
fi
```

```bash
git bisect start && git bisect good v1.4 && git bisect bad v1.4.1 && git bisect run ./test.sh
```

Ends with:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
6ae797e98a422cc6e1d18dd3c30f250bca1e594b
6a681352fd268da8e6316ea324f3248c09698cde
da9c62a86ba7c7a1c88fccf85418b2ec11f04e95
986469d0f4776efdd3810673eb35d619d73890d9
We cannot bisect more!
bisect run cannot continue any more
```

Those commits were skipped because they stacktraced:

```
running ./test.sh
++ cd ..
++ autopep8 --diff t.py
++ true
+ out='Traceback (most recent call last):
  File "/tmp/autopep8/venv/bin/autopep8", line 11, in <module>
    load_entry_point('\''autopep8'\'', '\''console_scripts'\'', '\''autopep8'\'')()
  File "/tmp/autopep8/autopep8.py", line 4044, in main
    fix_multiple_files(args.files, args, sys.stdout)
  File "/tmp/autopep8/autopep8.py", line 3956, in fix_multiple_files
    _fix_file((name, options, output))
  File "/tmp/autopep8/autopep8.py", line 3937, in _fix_file
    fix_file(*parameters)
  File "/tmp/autopep8/autopep8.py", line 3326, in fix_file
    fixed_source = fix_lines(fixed_source, options, filename=filename)
  File "/tmp/autopep8/autopep8.py", line 3306, in fix_lines
    fixed_source = fix.fix()
  File "/tmp/autopep8/autopep8.py", line 571, in fix
    aggressive=self.options.aggressive))
  File "/tmp/autopep8/autopep8.py", line 513, in _fix_source
    modified_lines = fix(result)
  File "/tmp/autopep8/autopep8.py", line 1266, in fix_w504
    target_operator = target[operator_position[0]:operator_position[1]]
TypeError: '\''NoneType'\'' object is not subscriptable'
+ grep -q Error:
+ exit 125
```

**Comment by hhatto** [comment]
fix in latest master.

version 1.4.2 just released.
https://pypi.org/project/autopep8/1.4.2/

Thanks.

**Comment by asottile** [comment]
seems to work, thanks for the fix!
