### ISSUE TITLE
autopep8.fix_file run from code ignores options passed as dict, fails on DotMap

### ISSUE THREAD

**Issue by czerus** [hhatto/autopep8#568]
I am trying to run autopep from code using `fix_file` and pass to it custom options (for now lets forget about any configuration file - it is no go for me now). If i define options as dict as mentioned in README I am getting following error:
```
  File "env/lib/python3.6/site-packages/autopep8.py", line 3516, in fix_file
    if options.in_place or options.diff or output:
AttributeError: 'dict' object has no attribute 'in_place'
```

I think it is because options is accessed using dot notation whereas it is a dict. To overcome this problem I used the `DotMap` module that converts dict to dict accessible by `.` and now the error is from pycodestyle:

```
Traceback (most recent call last):
  File "env/tests/run_formatter.py", line 97, in <module>
    CodeFormatter(args.fix).main()
  File "env/tests/run_formatter.py", line 34, in main
    to_fix = CodeFormatter._check_file(path)
  File "env/tests/run_formatter.py", line 67, in _check_file
    formatter_ok = autopep8.fix_file(pyfile, options=amended_options, apply_config=False)
  File "env/lib/python3.6/site-packages/autopep8.py", line 3522, in fix_file
    fixed_source = fix_lines(fixed_source, options, filename=filename)
  File "env/lib/python3.6/site-packages/autopep8.py", line 3476, in fix_lines
    results = _execute_pep8(pep8_options, contents)
  File "env/lib/python3.6/site-packages/autopep8.py", line 3008, in _execute_pep8
    checker.check_all()
  File "env/lib/python3.6/site-packages/pycodestyle.py", line 2184, in check_all
    for token in self.generate_tokens():
  File "env/lib/python3.6/site-packages/pycodestyle.py", line 2132, in generate_tokens
    self.maybe_check_physical(token)
  File "env/lib/python3.6/site-packages/pycodestyle.py", line 2142, in maybe_check_physical
    self.check_physical(token[4])
  File "env/lib/python3.6/site-packages/pycodestyle.py", line 2035, in check_physical
    result = self.run_check(check, argument_names)
  File "env/lib/python3.6/site-packages/pycodestyle.py", line 2023, in run_check
    return check(*arguments)
  File "env/lib/python3.6/site-packages/pycodestyle.py", line 290, in maximum_line_length
    if length > max_line_length and not noqa:
TypeError: '>' not supported between instances of 'int' and 'DotMap'
```
---

## Python Code
```python
import autopep8
autopep8.fix_file(pyfile, options={'diff': True, 'recursive': True, 'ignore-local': True, 'aggressive': 2, 'max-line-length': 120, 'exit-code': True}, apply_config=False)
```

## Command Line and Configuration
`.pep8`, `setup.cfg`, ...

Options that I am trying to push are:

```
{'diff': True, 'recursive': True, 'ignore-local': True, 'aggressive': 2, 'max-line-length': 120, 'exit-code': True}
```

I believe that something like showed here https://github.com/hhatto/autopep8/commit/7dc2bb933982adf1257351584d1e08aa2d09ed17 should be working properly but I cannot use it like that

## Your Environment
* Python version: 3.6.8
* autopep8 version: 1.5.3
* Platform: linux

**Comment by czerus** [comment]
I am able to overcome some of the problems by using SimpleNamespace:

```
options = SimpleNamespace(**amended_autopep_options)
autopep8.fix_file(pyfile, options=options)
```

but this still raises tons of errors about undefined values like: line_range, pep8_passes, ignore

It looks like using autopep from code requires to define all the switches that are handled/autoset during parsing via argparse.

**Comment by hhatto** [comment]
You can use the `fix_code()` function.
also included instructions on how to use it in the [README](https://github.com/hhatto/autopep8#use-as-a-module), so please refer to it.

```
import sys
import autopep8

pyfile = sys.argv[1]
with open(pyfile) as f:
    autopep8.fix_code(f.read(), options={'diff': True, 'recursive': True, 'ignore_local_config': True, 'aggressive': 2, 'max_line_length': 120, 'exit_code': True}, apply_config=False)
```
