### ISSUE TITLE
missing dependency on `packaging`

### ISSUE THREAD

**Issue by asottile** [hhatto/autopep8#702]
#696 contains an unconditional import of `packaging` which is not depended on by `autopep8`:

```console
Traceback (most recent call last):
  File "/home/asottile/.cache/pre-commit/repoanrqz_f1/py_env-python3.10/bin/autopep8", line 5, in <module>
    from autopep8 import main
  File "/home/asottile/.cache/pre-commit/repoanrqz_f1/py_env-python3.10/lib/python3.10/site-packages/autopep8.py", line 87, in <module>
    from packaging.version import parse as parse_version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by paugier** [comment]
Note that autopep8 2.0.3 is broken by this bug. It would be nice to quickly have a new release containing the fix.
